apiVersion: v1
kind: Service
metadata:
  name: oncall-tools-oauth2-proxy
  namespace: oncall-demo
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: oncall-tools-oauth2-proxy
  ports:
    - { name: http, port: 4180, targetPort: http, protocol: TCP }
